# Generated by Django 4.2.1 on 2023-05-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('cover', models.ImageField(upload_to='images/')),
                ('book', models.FileField(upload_to='books/')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Мужчина', 'Male'), ('Женщина', 'Female')], max_length=50)),
                ('study', models.CharField(choices=[('Да', 'yes'), ('Нет', 'no')], max_length=50)),
                ('work', models.CharField(choices=[('Да', 'yes'), ('Нет', 'no')], max_length=50)),
            ],
        ),
    ]
